### ISSUE TITLE
Broken link on "still meta-talking about sex"

### ISSUE THREAD

**Issue by palfrey** [heatherbooker/blog#9]
On https://heatherbooker.github.io/blog/2020/05/18/still-meta-talking-about-sex.html there's a link to https://heatherbooker.github.io/2020/04/25/lets-talk-about-sex-baby.html which is missing the `/blog/` bit

**Comment by heatherbooker** [comment]
Oh deer god jekyll and links are not a match made in heaven :sob: I think b1c5d9b3 and friends (aka surrounding commits) should have fixed it, but now the whole blog won't build, so... :shrug: You win some you lose some? :joy: 

Anyway thanks for pointing it out! :)

**Comment by heatherbooker** [comment]
Fixed in 817f4b4c637! :tada: Thanks again and happy reading :)
